# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# USERS
ian = User.create(name: "Ian", email: "ian@abc.com", password: "123", coach: false, img_src: "", source: "user")
ryan = User.create(name: "Ryan", email: "ryan@abc.com" , password: "123" , coach: false , img_src: "", source: "user")
ed = User.create(name: "Ed", email: "ed@abc.com", password: "123", coach: false, img_src: "", source: "user")
eelan = User.create(name: "Eelan", email: "eelan@abc.com", password: "123", coach: true, img_src: "", source: "user")
jeff = User.create(name: "Jeff", email: "jeff@abc.com", password: "123", coach: true, img_src: "", source: "user")
garry = User.create(name: "Garry", email: "garry@abc.com", password: "123", coach: false, img_src: "", source: "user")
jon = User.create(name: "Jon", email: "jon@abc.com", password: "123", coach: false, img_src: "", source: "user")
mike =  User.create(name: "Mike", email: "mike@abc.com", password: "123", coach: true, img_src: "", source: "user")
sydney = User.create(name: "Sydney", email: "sydney@abc.com", password: "123", coach: false, img_src: "", source: "user")
matt = User.create(name: "Matt", email: "matt@abc.com", password: "123", coach: false, img_src: "", source: "user")

# TEAMS
team1 = Team.create(name: "Team One", source: "team")
team2 = Team.create(name: "Team Two", source: "team")
team3 = Team.create(name: "Team Three", source: "team")
team4 = Team.create(name: "Team Four", source: "team")
team5 = Team.create(name: "Team Five", source: "team")
team6 = Team.create(name: "Team Six", source: "team")

# SHOWS
show1 = Show.create(name: "Show One", location: "Magnet", source: "show")
show2 = Show.create(name: "Show Two", location: "The Pit", source: "show")
show3 = Show.create(name: "Show Three", location: "UCB", source: "show")
show4 = Show.create(name: "Show Four", location: "UCB", source: "show")
show5 = Show.create(name: "Show Five", location: "Magnet", source: "show")
show6 = Show.create(name: "Show Six", location: "The Pit", source: "show")
show7 = Show.create(name: "Show Seven", location: "Magnet", source: "show")

# USERTEAMS
UserTeam.create(user_id: ian.id, team_id: team1.id)
UserTeam.create(user_id: ryan.id, team_id: team1.id)
UserTeam.create(user_id: eelan.id, team_id: team1.id)
UserTeam.create(user_id: ed.id, team_id: team1.id)
UserTeam.create(user_id: jeff.id, team_id: team1.id)
UserTeam.create(user_id: garry.id, team_id: team2.id)
UserTeam.create(user_id: jon.id, team_id: team2.id)
UserTeam.create(user_id: mike.id, team_id: team2.id)
UserTeam.create(user_id: ian.id, team_id: team2.id)
UserTeam.create(user_id: sydney.id, team_id: team3.id)
UserTeam.create(user_id: matt.id, team_id: team3.id)
UserTeam.create(user_id: jeff.id, team_id: team3.id)
UserTeam.create(user_id: garry.id, team_id: team4.id)
UserTeam.create(user_id: jon.id, team_id: team4.id)
UserTeam.create(user_id: ian.id, team_id: team5.id)
UserTeam.create(user_id: mike.id, team_id: team5.id)
UserTeam.create(user_id: matt.id, team_id: team5.id)
UserTeam.create(user_id: sydney.id, team_id: team5.id)
UserTeam.create(user_id: ed.id, team_id: team6.id)
UserTeam.create(user_id: ian.id, team_id: team6.id)

# USERSHOWS
UserShow.create(user_id: ian.id, show_id: show1.id)
UserShow.create(user_id: ryan.id, show_id: show1.id)
UserShow.create(user_id: eelan.id, show_id: show1.id)
UserShow.create(user_id: ed.id, show_id: show1.id)
UserShow.create(user_id: jeff.id, show_id: show1.id)
UserShow.create(user_id: garry.id, show_id: show2.id)
UserShow.create(user_id: jon.id, show_id: show2.id)
UserShow.create(user_id: mike.id, show_id: show2.id)
UserShow.create(user_id: ian.id, show_id: show2.id)
UserShow.create(user_id: sydney.id, show_id: show3.id)
UserShow.create(user_id: matt.id, show_id: show3.id)
UserShow.create(user_id: jeff.id, show_id: show3.id)
UserShow.create(user_id: garry.id, show_id: show4.id)
UserShow.create(user_id: jon.id, show_id: show4.id)
UserShow.create(user_id: ian.id, show_id: show5.id)
UserShow.create(user_id: mike.id, show_id: show5.id)
UserShow.create(user_id: matt.id, show_id: show5.id)
UserShow.create(user_id: sydney.id, show_id: show5.id)
UserShow.create(user_id: ed.id, show_id: show6.id)
UserShow.create(user_id: ian.id, show_id: show6.id)

# NOTES
Note.create(content: "I'm the best!", user_id: ian.id)
Note.create(content: "Hello!", user_id: ryan.id)
Note.create(content: "Meh.", user_id: eelan.id)
Note.create(content: "I'm so excited!", user_id: ed.id)
Note.create(content: "Ian missed my blog!", user_id: jeff.id)
Note.create(content: "Yo guys, blog time.", user_id: garry.id)
Note.create(content: "Seriously guys, blogs!", user_id: jon.id)
Note.create(content: "I like cats.", user_id: mike.id)
Note.create(content: "You heard it here first, folks.", user_id: ian.id)
Note.create(content: "Ballons are fun.", user_id: sydney.id)
Note.create(content: "I like soccer.", user_id: matt.id)
Note.create(content: "What up!!?!", user_id: jeff.id)
Note.create(content: "My name is spelt with two R's", user_id: garry.id)
Note.create(content: "NOOOOOO!!! Okay yes.", user_id: jon.id)
Note.create(content: "Still the best!", user_id: ian.id)
Note.create(content: "I also like puns.", user_id: mike.id)
Note.create(content: "Lol.", user_id: matt.id)
Note.create(content: "Rainbows are also fun.", user_id: sydney.id)
Note.create(content: "Got my auth working!", user_id: ed.id)
Note.create(content: "THE.......BEST!", user_id: ian.id)

# PRACTICES (GONNA CUT THIS FOR NOW [WILL NEED A JOIN TABLE BECAUSE MULTIPLE USERS CAN HAVE A PRACTICE, AND WHY IS THIS HELPFUL FOR THE USER?])
# p1 = Practice.create(name: "P One" , location: , user_id: )
# p2 = Practice.create(name: "P Two", location: , user_id: )
# p3 = Practice.create(name: "P Three", location: , user_id: )
# p4 = Practice.create(name: "P Four", location: , user_id: )
# p5 = Practice.create(name: "P Five", location: , user_id: )
# p6 = Practice.create(name: "P Six", location: , user_id: )
# p7 = Practice.create(name: "P Seven", location: , user_id: )
# p8 = Practice.create(name: "P Eight", location: , user_id: )
# p9 = Practice.create(name: "P Nine", location: , user_id: )
# p10 = Practice.create(name: "P Ten", location: , user_id: )
